### ISSUE TITLE
On reveal current sentence

### ISSUE THREAD

**Issue by brederic** [brederic/Remember-When#34]
The sentence appears, but in the wrong rotation, and this error appears
ly_studio.js:15 During notification revealCurrentSentence
Cannot read property 'className' of null
TypeError: Cannot read property 'className' of null
    at Object.removeClass (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:100323)
    at Object.notif_revealCurrentSentence (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/games/rememberwhen/999999-9999//rememberwhen.js?1477770962576:833:26)
    at _252.<anonymous> (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:32115)
    at _252._268 [as onrevealCurrentSentence](http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:58239)
    at Function.on.emit (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:52514)
    at Function.on.emit (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:53296)
    at _252.emit (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:56917)
    at Object.publish (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:56478)
    at Object.publish (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/dojoroot/dojo/dojo.js:15:48761)
    at Object.dispatchNotification (http://1.studio.boardgamearena.com:8081/data/themereleases/151226-1240/js/modules/layer/ly_studio.js:15:479604)

**Comment by brederic** [comment]
Trying to duplicate....
- 3 player express start does not manifest this problem
- 3 player normal does not manifest this problem
